# Generated by Django 4.0.3 on 2022-03-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_auto_20210721_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='image',
        ),
    ]
